# Generated by Django 3.2.12 on 2022-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QBODetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=250, null=True)),
                ('realm_id', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
